// `vibeshield completion <shell>` — shell completion scripts.
//
// Completion is the single highest-leverage usability feature a CLI can add
// for free: it turns "which flag was it again?" into Tab, and it teaches the
// command surface without the user reading the manual. The scripts are
// generated here rather than checked in as static files so they can never
// describe a command that no longer exists — every verb and flag below comes
// from the same tables the parser uses.
package main

import (
	"fmt"
	"io"
	"strings"
)

// completionCommands is the verb list offered for the first argument.
var completionCommands = []string{
	"scan", "fix", "init", "doctor", "search", "rules", "agents",
	"completion", "version", "help", "ui",
}

// completionFlags maps a verb to the flags it accepts. Kept next to the help
// text on purpose: if a flag is added, both have to be touched, and the
// completion test fails until they are.
var completionFlags = map[string][]string{
	"scan":   {"--diff", "--staged", "--format", "--config", "--mode", "--rules", "--online", "--max-cols", "--no-color", "-v", "--verbose"},
	"fix":    {"--dry-run", "--yes", "--report", "--config", "--rules", "--no-color", "-v", "--verbose"},
	"init":   {"--mode", "--dry-run", "--force", "--no-hook", "--no-workflow", "--no-scan", "--no-color"},
	"doctor": {"--config", "--format", "--no-color", "-v", "--verbose"},
	"search": {"--list", "--rules", "--agents", "--limit", "--format", "--no-color"},
	"rules":  {"--limit", "--format", "--no-color"},
	"agents": {"--body", "--markdown"},
	"help":   {},
}

// completionValueFlags maps a flag to its value choices, for the shells that
// can complete an argument.
var completionValueFlags = map[string][]string{
	"--format":   {"pretty", "json", "github", "sarif"},
	"--mode":     {"off", "warn", "block-on-critical", "block-on-high+"},
	"--diff":     {"main", "master", "HEAD~1", "-"},
	"--config":   nil, // nil means "complete a file path"
	"--report":   nil,
	"--rules":    nil,
	"--limit":    nil,
	"--max-cols": nil,
}

func cmdCompletion(args []string, stdout, stderr io.Writer) int {
	fl := newFlagSet("completion", stderr)
	fl.Usage = func() { printUsage(stderr, "completion") }
	if err := fl.Parse(args); err != nil {
		return usageExit(err)
	}
	if fl.NArg() == 0 {
		fmt.Fprint(stderr, "vibeshield: completion needs a shell name\n\n")
		printUsage(stderr, "completion")
		return 2
	}
	shell := strings.ToLower(fl.Arg(0))
	var script string
	switch shell {
	case "bash":
		script = bashCompletion()
	case "zsh":
		script = zshCompletion()
	case "fish":
		script = fishCompletion()
	case "powershell", "pwsh":
		script = pwshCompletion()
	default:
		fmt.Fprintf(stderr, "vibeshield: unknown shell %q (bash | zsh | fish | powershell)\n", fl.Arg(0))
		return 2
	}
	fmt.Fprint(stdout, script)
	return 0
}

func bashCompletion() string {
	var b strings.Builder
	b.WriteString("# vibeshield bash completion — generated by `vibeshield completion bash`.\n")
	b.WriteString("# Install:  vibeshield completion bash >> ~/.bashrc\n\n")
	b.WriteString("_vibeshield_complete() {\n")
	b.WriteString("  local cur prev cmd i\n")
	b.WriteString("  COMPREPLY=()\n")
	b.WriteString("  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("  prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n\n")
	b.WriteString("  case \"$prev\" in\n")
	b.WriteString("    --format) COMPREPLY=( $(compgen -W \"pretty json github sarif\" -- \"$cur\") ); return ;;\n")
	b.WriteString("    --mode)   COMPREPLY=( $(compgen -W \"off warn block-on-critical block-on-high+\" -- \"$cur\") ); return ;;\n")
	b.WriteString("    --diff)   COMPREPLY=( $(compgen -W \"main master HEAD~1 -\" -- \"$cur\") ); return ;;\n")
	b.WriteString("    --config|--report|--rules) COMPREPLY=( $(compgen -f -- \"$cur\") ); return ;;\n")
	b.WriteString("  esac\n\n")
	b.WriteString("  # First non-flag word is the subcommand.\n")
	b.WriteString("  cmd=\"\"\n")
	b.WriteString("  for ((i=1; i<COMP_CWORD; i++)); do\n")
	b.WriteString("    case \"${COMP_WORDS[i]}\" in -*) ;; *) cmd=\"${COMP_WORDS[i]}\"; break ;; esac\n")
	b.WriteString("  done\n\n")
	b.WriteString("  local global=\"--help -h --no-color\"\n")
	b.WriteString("  if [ -z \"$cmd\" ]; then\n")
	b.WriteString("    COMPREPLY=( $(compgen -W \"")
	b.WriteString(strings.Join(completionCommands, " "))
	b.WriteString(" $global\" -- \"$cur\") )\n")
	b.WriteString("    return\n")
	b.WriteString("  fi\n\n")
	b.WriteString("  local flags=\"\"\n")
	b.WriteString("  case \"$cmd\" in\n")
	for _, cmd := range []string{"scan", "fix", "init", "doctor", "search", "rules", "agents"} {
		fmt.Fprintf(&b, "    %s) flags=\"%s\" ;;\n", cmd, strings.Join(completionFlags[cmd], " "))
	}
	b.WriteString("    completion) COMPREPLY=( $(compgen -W \"bash zsh fish powershell\" -- \"$cur\") ); return ;;\n")
	b.WriteString("  esac\n\n")
	b.WriteString("  if [ \"${cur:0:1}\" = \"-\" ]; then\n")
	b.WriteString("    COMPREPLY=( $(compgen -W \"$flags $global\" -- \"$cur\") )\n")
	b.WriteString("  else\n")
	b.WriteString("    COMPREPLY=( $(compgen -d -- \"$cur\") )\n")
	b.WriteString("  fi\n")
	b.WriteString("}\n")
	b.WriteString("complete -o bashdefault -o default -F _vibeshield_complete vibeshield\n")
	return b.String()
}

func zshCompletion() string {
	var b strings.Builder
	b.WriteString("#compdef vibeshield\n")
	b.WriteString("# vibeshield zsh completion — generated by `vibeshield completion zsh`.\n")
	b.WriteString("# Install:  vibeshield completion zsh > \"${fpath[1]}/_vibeshield\"\n\n")
	b.WriteString("_vibeshield() {\n")
	b.WriteString("  local -a commands\n")
	b.WriteString("  commands=(\n")
	for _, d := range docs() {
		fmt.Fprintf(&b, "    '%s:%s'\n", d.Name, zshQuote(d.Summary))
	}
	b.WriteString("  )\n\n")
	b.WriteString("  _arguments -C \\\n")
	b.WriteString("    '(-h --help)'{-h,--help}'[show help]' \\\n")
	b.WriteString("    '--no-color[disable color]' \\\n")
	b.WriteString("    '1:command:->command' \\\n")
	b.WriteString("    '*::arg:->args'\n\n")
	b.WriteString("  case $state in\n")
	b.WriteString("    command) _describe 'command' commands ;;\n")
	b.WriteString("    args)\n")
	b.WriteString("      case $words[1] in\n")
	for _, cmd := range []string{"scan", "fix", "init", "doctor", "search", "rules", "agents"} {
		fmt.Fprintf(&b, "        %s) _arguments \\\n", cmd)
		for _, f := range completionFlags[cmd] {
			fmt.Fprintf(&b, "          '%s' \\\n", zshFlagSpec(f))
		}
		b.WriteString("          '*:path:_files' ;;\n")
	}
	b.WriteString("        completion) _values 'shell' bash zsh fish powershell ;;\n")
	b.WriteString("      esac\n")
	b.WriteString("    ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("}\n\n")
	b.WriteString("_vibeshield \"$@\"\n")
	return b.String()
}

// zshFlagSpec renders one flag for zsh's _arguments, adding the value
// description for flags that take one.
func zshFlagSpec(flag string) string {
	values, ok := completionValueFlags[flag]
	if !ok {
		return flag + "[ ]"
	}
	if len(values) == 0 {
		return flag + "=[file]:file:_files"
	}
	return fmt.Sprintf("%s=[%s]:value:(%s)", flag, strings.Join(values, "|"), strings.Join(values, " "))
}

// zshQuote escapes the single quotes _describe cannot tolerate in a summary.
func zshQuote(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "'", ""), ":", " -")
}

func fishCompletion() string {
	var b strings.Builder
	b.WriteString("# vibeshield fish completion — generated by `vibeshield completion fish`.\n")
	b.WriteString("# Install:  vibeshield completion fish > ~/.config/fish/completions/vibeshield.fish\n\n")
	b.WriteString("complete -c vibeshield -f\n\n")
	b.WriteString("# Commands\n")
	for _, d := range docs() {
		fmt.Fprintf(&b, "complete -c vibeshield -n '__fish_use_subcommand' -a %s -d '%s'\n",
			d.Name, strings.ReplaceAll(d.Summary, "'", ""))
	}
	b.WriteString("\n# Flags\n")
	for _, cmd := range []string{"scan", "fix", "init", "doctor", "search", "rules", "agents"} {
		cond := fmt.Sprintf("__fish_seen_subcommand_from %s", cmd)
		for _, f := range completionFlags[cmd] {
			name := strings.TrimLeft(f, "-")
			line := fmt.Sprintf("complete -c vibeshield -n '%s' -l %s", cond, name)
			if values, ok := completionValueFlags[f]; ok {
				if len(values) > 0 {
					line += fmt.Sprintf(" -x -a '%s'", strings.Join(values, " "))
				} else {
					line += " -r -F"
				}
			}
			b.WriteString(line + "\n")
		}
	}
	b.WriteString("\ncomplete -c vibeshield -n '__fish_seen_subcommand_from completion' -x -a 'bash zsh fish powershell'\n")
	b.WriteString("complete -c vibeshield -s h -l help -d 'Show help'\n")
	b.WriteString("complete -c vibeshield -l no-color -d 'Disable color'\n")
	return b.String()
}

func pwshCompletion() string {
	var b strings.Builder
	b.WriteString("# vibeshield PowerShell completion — generated by `vibeshield completion powershell`.\n")
	b.WriteString("# Install:  vibeshield completion powershell | Out-String | Invoke-Expression\n\n")
	b.WriteString("Register-ArgumentCompleter -Native -CommandName vibeshield -ScriptBlock {\n")
	b.WriteString("  param($wordToComplete, $commandAst, $cursorPosition)\n")
	b.WriteString("  $elements = $commandAst.CommandElements\n")
	b.WriteString("  $cmd = $null\n")
	b.WriteString("  for ($i = 1; $i -lt $elements.Count; $i++) {\n")
	b.WriteString("    $t = $elements[$i].ToString()\n")
	b.WriteString("    if (-not $t.StartsWith('-')) { $cmd = $t; break }\n")
	b.WriteString("  }\n\n")
	b.WriteString("  $commands = @(")
	quoted := make([]string, 0, len(completionCommands))
	for _, c := range completionCommands {
		quoted = append(quoted, "'"+c+"'")
	}
	b.WriteString(strings.Join(quoted, ", "))
	b.WriteString(")\n\n")
	b.WriteString("  $flags = @{\n")
	for _, cmd := range []string{"scan", "fix", "init", "doctor", "search", "rules", "agents"} {
		q := make([]string, 0, len(completionFlags[cmd]))
		for _, f := range completionFlags[cmd] {
			q = append(q, "'"+f+"'")
		}
		fmt.Fprintf(&b, "    %s = @(%s)\n", cmd, strings.Join(q, ", "))
	}
	b.WriteString("  }\n\n")
	b.WriteString("  $candidates = if (-not $cmd) { $commands }\n")
	b.WriteString("               elseif ($flags.ContainsKey($cmd)) { $flags[$cmd] }\n")
	b.WriteString("               else { @() }\n\n")
	b.WriteString("  $candidates | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {\n")
	b.WriteString("    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}
